services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-pulse
    restart: always
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - postgres
    expose:
      - ${APP_PORT}

  postgres:
    platform: linux/amd64
    image: postgres:17-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA='/var/lib/postgresql/data/pgdata'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - app
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infra/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DB_PORT}:${DB_PORT}

  grafana:
    image: grafana/grafana:latest
    restart: always
    env_file:
      - .env
    expose:
      - ${GF_PORT}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning/datasources
    depends_on:
      - postgres
    networks:
      - app
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: ${DB_HOST}
      GF_DATABASE_PORT: ${DB_PORT}
      GF_DATABASE_NAME: ${GRAFANA_DB}
      GF_DATABASE_USER: ${GRAFANA_ADMIN_USER}
      GF_DATABASE_PASSWORD: ${GRAFANA_ADMIN_PASS}
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP}

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    env_file:
      - .env
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    volumes:
      - ./infra/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - app
      - grafana
      - postgres
    networks:
      - app
    environment:
      NGINX_ENVSUBST_FILTER: ^(APP_PORT|GF_PORT|LISTEN_PORT)$

networks:
  app:
    driver: bridge

volumes:
  postgres-data:
  grafana_data: