services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-pulse
    restart: always
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    networks:
      - app
    expose:
      - ${APP_PORT}

#  clickhouse:
#      image: clickhouse/clickhouse-server:latest
#      container_name: clickhouse-server
#      ports:
#        - "8123:8123"
#        - "9000:9000"
#      volumes:
#        - clickhouse_data:/var/lib/clickhouse
#        - ./config/config.xml:/etc/clickhouse-server/config.d/docker.xml
#        - ./config/users.xml:/etc/clickhouse-server/users.d/docker.xml
#      environment:
#        CLICKHOUSE_DB: analytics
#      ulimits:
#        nofile:
#          soft: 262144
#          hard: 262144
#      deploy:
#        resources:
#          limits:
#            memory: 4G
#          reservations:
#            memory: 2G

#  clickhouse:
#    image: clickhouse/clickhouse-server:latest
#    ports:
#      - "8123:8123"

#  superset:
#    image: apache/superset:latest
#    restart: always
#    environment:
#      SUPERSET_LOAD_EXAMPLES: "no"
#      SUPERSET_SECRET_KEY: "supersecret"
#      SUPERSET_WEBSERVER_DOMAINS: localhost
#      SUPERSET_APP_ROOT: "/superset"
#      PREFERRED_URL_SCHEME: http
#    ports:
#      - "3000:8088"
#    networks:
#      - app

#  nginx:
#    image: nginx
#    container_name: nginx
#    restart: always
#    env_file:
#      - .env
#    ports:
#      - "${LISTEN_PORT}:${LISTEN_PORT}"
#    volumes:
#      - ./infra/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
#    depends_on:
#      - app
#      - postgres
#      - superset
#    networks:
#      - app
#    environment:
#      NGINX_ENVSUBST_FILTER: ^(APP_PORT|LISTEN_PORT)$

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    networks:
      - app
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app:
    driver: bridge

volumes:
  redis-data:
