-- БД для графаны
CREATE DATABASE ${GRAFANA_DB};
CREATE USER ${GRAFANA_ADMIN_USER} WITH PASSWORD '${GRAFANA_ADMIN_PASS}';
ALTER DATABASE ${GRAFANA_DB} OWNER TO ${GRAFANA_ADMIN_USER};

-- readonly пользователь для DataSource Grafana
CREATE USER ${GRAFANA_RO_USER} WITH PASSWORD '${GRAFANA_RO_PASS}';
GRANT CONNECT ON DATABASE ${DB_NAME} TO ${GRAFANA_RO_USER};
GRANT USAGE ON SCHEMA public TO ${GRAFANA_RO_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${GRAFANA_RO_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON TABLES TO ${GRAFANA_RO_USER};