apiVersion: 1

datasources:
  - name: PostgreSQL App DB
    type: postgres
    uid: app-db-ds
    isDefault: true
    url: ${DB_HOST}:${DB_PORT}
    user: ${GRAFANA_RO_USER}
    database: ${DB_NAME}
    secureJsonData:
      password: ${GRAFANA_RO_PASS}
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timeInterval: "1s"
      maxOpenConns: 100
      maxIdleConns: 10
      connMaxLifetime: 300
